services:
  hyperhdr:
    image: "thomy90/hyperhdr:${IMAGE_VERSION:-latest}"
    container_name: "hyperhdr"
    restart: "always"
    networks:
      - "reverse-proxy"
    expose:
      - "8090"
    command:
      - "--userdata=/data"
      - "--verbose"
    volumes:
      - "./data/:/data/"
    devices:
      - "${CAPTURE_DEVICE-/dev/video0}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hyperhdr.rule=Host(`hyperhdr.home.tastic`)"
      - "homepage.group=Media & Entertainment"
      - "homepage.name=HyperHDR"
      - "homepage.icon=hyperion.png"
      - "homepage.href=https://hyperhdr.home.tastic"
      - "homepage.description=Ambilight"


networks:
  reverse-proxy:
    external: true
