services:
  hyperhdr:
    image: "thomy90/hyperhdr:${IMAGE_VERSION:-21.0.0.0beta2}"
    container_name: "hyperhdr"
    restart: "always"
    networks:
      - "reverse-proxy"
    ports:
      - "9091:8090"  # Adjust according to your port you want to use
    command:
      - "--userdata=/data"
      - "--verbose"
    volumes:
      - "./data/:/data/"
    devices:
      - /dev/video0  # Adjust according to your capture device

networks:
  reverse-proxy:
    external: true
