services:
  hyperhdr:
    image: "thomy90/hyperhdr:${IMAGE_VERSION}"
    container_name: "hyperhdr"
    restart: "always"
    networks:
      - "reverse-proxy"
    ports:
      - "9091:8090"
    command:
      - "--userdata=/data"
      - "--verbose"
    volumes:
      - "./data/:/data/"
    devices:
      - /dev/video0

networks:
  reverse-proxy:
    external: true
