name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set VERSION based on ref type
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          push: false
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: |
            ${{ vars.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ vars.IMAGE_NAME }}:latest
